### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Misael32** [NatanielCZN/TP_MercadoLiebre#1]
1 - Cumple con la estructura del sitio. 

![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/93827335/10fc8cbe-9fb7-4037-8511-f5182d00b031)
![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/93827335/c138c25b-2ab6-4106-a1a7-7157e1f8f7ae)
2 -No cumple ya que los iconos no tienen el tamaño de 2em y tampoco el un margen inferior de separación de
10 píxeles.
3 -El sitio se adapta a distintas resoluciones de pantalla por lo tanto cumple con lo solicitado.
4 -El sitio cuenta con un formulario de registro de usuarios por lo tanto cumple con lo solicitado.
5 -El sitio cuenta con un formulario de login por lo tanto cumple con lo solicitado.
6 -Si se muestran mensajes de error cuando un usuario coloca información equivocada en un campo de los formularios pero cuando se presiona el botón enviar debería redireccionar al pagina de inicio lo cual no hace.
7 -El search bar es un formulario por lo tanto si cumple con lo solicitado.
8 -Si se utilizan animaciones y propiedades de transición de CSS por lo tanto cumple con lo solicitado.
9 -Consideró que en general todo el sitio esta bien, lo felicito le quedó muy bien. 

![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/93827335/c473a6ad-3e97-48e4-a1ec-ef87de5dfff1)
10 -Tal vez podria mejorar el apartado de la barra de navegacion cuando esta en resolucion para tablets ya que para mi no es correcto que quede de esa manera.

**Comment by NatanielCZN** [comment]
Muchas gracias por la devolucion, estare corrigindo los items señalados cuanto antes. 👍

**Comment by NatanielCZN** [comment]
Correcciones realizadas, ajuste el tamaño de los iconos y ajuste la barra de navegacion para tablets.

![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/61957095/e028a248-c02d-4092-bfd8-76e848939c96)
