### ISSUE TITLE
Observaciones Menores

### ISSUE THREAD

**Issue by Manustoteles** [NatanielCZN/TP_MercadoLiebre#2]
Antes que nada excelente la pagina, muchos detalles, se nota que hubo tiempo y dedicacion.-
Observe que ya le hicieron un issue anterior donde le han hecho las observaciones de lo pendiente, por lo que solo puedo hacer sugerencias de mejoras a los fines de que el sitio quede mas lindo, que de por si ya lo esta:
veria el comportamiento de los liks en esta resolucion: 
![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/141280392/5f38e68c-57e2-4a48-bde1-13d77cab4482)
mejoraria la lineacion de los checks de comprador y vendedor mas centrado respecto del input de la izquierda: 
![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/141280392/37f3c35f-cc82-49e8-8a23-cc2daa2ec8cb)
Pondria los cuadraditos de check todos en una misma linea en categorias: 
![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/141280392/d31a9d7e-487d-4c5e-9d88-a151fa2d86a2)

son pequeños detalles ya que el resto esta impecable, saludos y excelente trabajo

**Comment by NatanielCZN** [comment]
Correcciones realizadas. Gracias por el aporte.

![image](https://github.com/NatanielCZN/TP_MercadoLiebre/assets/61957095/653b5379-aea6-4a9a-8965-b10ddee73626)
